stages:
  - lint

lint-backend:
  stage: lint
  script:
    - cd backend
    - pip install -r requirements.txt
    - pip install pylint
    - pylint **/*.py  # Adjust as needed based on your directory structure
