image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build

build-backend:
  stage: build
  tags:
    - shared-runner-tag # replace this with the actual tag of the shared runner
  before_script:
    - docker info
  script:
    - cd backend
    - docker build -t my-backend-image .

build-frontend:
  stage: build
  tags:
    - shared-runner-tag # replace this with the actual tag of the shared runner
  before_script:
    - docker info
  script:
    - cd frontend
    - docker build -f .Dockerfile -t my-frontend-image .
