stages:
  - build

build-backend:
  stage: build
  tags:
    - docker-runner
  before_script:
    - docker info
  script:
    - cd backend
    - docker build -t my-backend-image .

build-frontend:
  stage: build
  tags:
    - docker-runner
  before_script:
    - docker info
  script:
    - cd frontend
    - docker build -f .Dockerfile -t my-frontend-image .
