include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - build

build-proxy-img-prod:
  extends: .build-image-using-kaniko
  stage: build
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY/nse/subcellular/backend
    REGISTRY_IMAGE_TAG: latest
    CI_PROJECT_DIR: /builds/nse/subcellular/backend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
