version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - ./tmp/mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - subcellular
  backend:
    image: sc-svc
    volumes:
      - .:/app
      - ./tmp:/data
    ports:
      - "8888:8000"
    networks:
      - subcellular
    environment:
      - DEBUG=True
      - DB_HOST=mongo
      - PYTHONUNBUFFERED=True
      - "MONGO_URI=subcellular_app"
    depends_on:
      - "mongo"
    working_dir: /app
    entrypoint:
      ["wait-for-it", "-t", "60", "mongo:27017", "--", "python3", "main.py"]
  sim_worker:
    image: sc-svc
    depends_on:
      - backend
    networks:
      - subcellular
    volumes:
      - .:/app
      - ./tmp/geometries:/data/geometries
    environment:
      - MASTER_HOST=backend
      - DEBUG=True
      - PYTHONUNBUFFERED=True
    working_dir: /app
    entrypoint:
      ["wait-for-it", "-t", "60", "backend:8000", "--", "python3", "main.py"]

networks:
  subcellular:
    name: subcellular
