version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./tmp/mongo_data:/data/db
    ports:
      - "27017:27017"
  backend:
    image: sc-svc
    volumes:
      - ./subcellular_experiment:/usr/local/lib/python3.7/site-packages/subcellular_experiment
      - ./tmp/geometries:/data/geometries
    ports:
      - "8888:8000"
    environment:
      - DEBUG=True
      - DB_HOST=mongo
      - PYTHONUNBUFFERED=True
      - "MONGO_URI=subcellular_app"
    depends_on:
      - 'mongo'
    working_dir: /app
    entrypoint: ["wait-for-it", "-t", "60", "mongo:27017", "--", "python", "-m", "subcellular_experiment.main"]
  sim_worker:
    image: sc-svc
    depends_on:
      - backend
    volumes:
      - ./subcellular_experiment:/usr/local/lib/python3.7/site-packages/subcellular_experiment
      - ./tmp/geometries:/data/geometries
    environment:
      - MASTER_HOST=backend
      - DEBUG=True
      - PYTHONUNBUFFERED=True
    depends_on:
      - "backend"
    working_dir: /app
    entrypoint: ["wait-for-it", "-t", "60", "backend:8000", "--", "python", "-m", "subcellular_experiment.main"]
